// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class AccountCode
    {
        public AccountCode()
        {
            BillableItemType = new HashSet<BillableItemType>();
        }

        public string AccountCode1 { get; set; }
        public string AccountCodeName { get; set; }
        public string AccountGroupCode { get; set; }
        public string AccountGroupCodeName { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<BillableItemType> BillableItemType { get; set; }
    }
}