// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ActivityType
    {
        public ActivityType()
        {
            Activity = new HashSet<Activity>();
            ServiceCode = new HashSet<ServiceCode>();
        }

        public string ActivityTypeCode { get; set; }
        public string ActivityTypeDescription { get; set; }
        public bool? IsActive { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ICollection<Activity> Activity { get; set; }
        public virtual ICollection<ServiceCode> ServiceCode { get; set; }
    }
}