// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class Activity
    {
        public Activity()
        {
            ActivityDetail = new HashSet<ActivityDetail>();
        }

        public int Id { get; set; }
        public string ActivityTypeCode { get; set; }
        public int JobId { get; set; }
        public int? SuperServiceOrderId { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ActivityType ActivityTypeCodeNavigation { get; set; }
        public virtual TaskOrder Job { get; set; }
        public virtual Shipment SuperServiceOrder { get; set; }
        public virtual ICollection<ActivityDetail> ActivityDetail { get; set; }
    }
}