// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ActivityDetail
    {
        public int Id { get; set; }
        public int ActivityId { get; set; }
        public int? ProviderVendorId { get; set; }
        public string ActivityDetailType { get; set; }
        public DateTime? StartDateTime { get; set; }
        public DateTime? EndDateTime { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual Vendor ProviderVendor { get; set; }
    }
}