// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class Address
    {
        public Address()
        {
            AuthorizedRepresentativeDestinationAddress = new HashSet<AuthorizedRepresentative>();
            AuthorizedRepresentativeOriginAddress = new HashSet<AuthorizedRepresentative>();
            JobDestinationAddress = new HashSet<Job>();
            JobOriginAddress = new HashSet<Job>();
            TaskOrderDestinationDutyStationAddress = new HashSet<TaskOrder>();
            TaskOrderOriginDutyStationAddress = new HashSet<TaskOrder>();
            Vendor = new HashSet<Vendor>();
        }

        public int Id { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string CountryCode3 { get; set; }
        public double? Longitude { get; set; }
        public double? Latitude { get; set; }
        public string Display { get; set; }
        public string AdditionalAddressInfo { get; set; }
        public string Type { get; set; }

        public virtual ICollection<AuthorizedRepresentative> AuthorizedRepresentativeDestinationAddress { get; set; }
        public virtual ICollection<AuthorizedRepresentative> AuthorizedRepresentativeOriginAddress { get; set; }
        public virtual ICollection<Job> JobDestinationAddress { get; set; }
        public virtual ICollection<Job> JobOriginAddress { get; set; }
        public virtual ICollection<TaskOrder> TaskOrderDestinationDutyStationAddress { get; set; }
        public virtual ICollection<TaskOrder> TaskOrderOriginDutyStationAddress { get; set; }
        public virtual ICollection<Vendor> Vendor { get; set; }
    }
}