// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class AuthorizedRepresentativePhone
    {
        public int AuthorizedRepresentativeId { get; set; }
        public int PhoneId { get; set; }

        public virtual AuthorizedRepresentative AuthorizedRepresentative { get; set; }
        public virtual Phone Phone { get; set; }
    }
}