// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class AuthorizedRepresentative
    {
        public AuthorizedRepresentative()
        {
            AuthorizedRepresentativePhone = new HashSet<AuthorizedRepresentativePhone>();
        }

        public int Id { get; set; }
        public int JobId { get; set; }
        public string SourceIdentifier { get; set; }
        public string SourceName { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PrimaryEmail { get; set; }
        public string AlternateEmail { get; set; }
        public string PrimaryCommunicationPreference { get; set; }
        public string SecondaryCommunicationPreference { get; set; }
        public int? OriginAddressId { get; set; }
        public int? DestinationAddressId { get; set; }
        public DateTime EffectiveStartDateTime { get; set; }
        public DateTime? EffectiveEndDateTime { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Address DestinationAddress { get; set; }
        public virtual Job Job { get; set; }
        public virtual Address OriginAddress { get; set; }
        public virtual ICollection<AuthorizedRepresentativePhone> AuthorizedRepresentativePhone { get; set; }
    }
}