// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class BillableItem
    {
        public BillableItem()
        {
            BillableItemAdjustment = new HashSet<BillableItemAdjustment>();
            GPTransaction = new HashSet<GPTransaction>();
        }

        public int Id { get; set; }
        public int SuperServiceOrderId { get; set; }
        public int? BillableItemTypeId { get; set; }
        public string BillableItemStatusIdentifier { get; set; }
        public string BillToType { get; set; }
        public int? BillToTransfereeId { get; set; }
        public int? BillToAccountEntityId { get; set; }
        public int? BillToVendorId { get; set; }
        public int? InvoiceId { get; set; }
        public string Description { get; set; }
        public string BillingCurrency { get; set; }
        public string BillingCurrencySymbol { get; set; }
        public bool IsOriginalAccrual { get; set; }
        public decimal? OriginalAccrualAmountBillingCurrency { get; set; }
        public decimal? OriginalAccrualAmountUSD { get; set; }
        public DateTimeOffset? OriginalAccrualPostedDateTime { get; set; }
        public string OriginalAccrualPostedBy { get; set; }
        public decimal? AccrualAmountBillingCurrency { get; set; }
        public decimal? AccrualAmountUSD { get; set; }
        public decimal? AccrualExchangeRate { get; set; }
        public DateTime? AccrualExchangeRateDateTime { get; set; }
        public DateTime? AccrualFinancialPeriodDateTime { get; set; }
        public DateTimeOffset? AccrualPostedDateTime { get; set; }
        public string AccrualPostedBy { get; set; }
        public int? SequenceOverAccountCode { get; set; }
        public string GPDocNum { get; set; }
        public bool IsAccrualAdjusted { get; set; }
        public string AccrualAdjustmentBy { get; set; }
        public DateTime? AccrualAdjustmentDateTime { get; set; }
        public decimal? OriginalActualAmountBillingCurrency { get; set; }
        public decimal? OriginalActualAmountUSD { get; set; }
        public DateTimeOffset? OriginalActualPostedDateTime { get; set; }
        public string OriginalActualPostedBy { get; set; }
        public decimal? ActualAmountBillingCurrency { get; set; }
        public decimal? ActualAmountUSD { get; set; }
        public decimal? ActualExchangeRate { get; set; }
        public DateTime? ActualExchangeRateDateTime { get; set; }
        public DateTime? ActualFinancialPeriodDateTime { get; set; }
        public DateTime? ActualPostedDateTime { get; set; }
        public string ActualPostedBy { get; set; }
        public bool IsActualAdjusted { get; set; }
        public string ActualAdjustmentBy { get; set; }
        public DateTime? ActualAdjustmentDateTime { get; set; }
        public decimal? WriteOffAmountUSD { get; set; }
        public string WriteOffReason { get; set; }
        public string WriteOffExplanation { get; set; }
        public string WriteOffModifiedBy { get; set; }
        public DateTimeOffset? WriteOffModifiedDateTime { get; set; }
        public string VoidedBy { get; set; }
        public DateTimeOffset? VoidedDateTime { get; set; }
        public DateTime? VoidedFinancialPeriodDate { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual AccountEntity BillToAccountEntity { get; set; }
        public virtual Transferee BillToTransferee { get; set; }
        public virtual Vendor BillToVendor { get; set; }
        public virtual BillableItemStatus BillableItemStatusIdentifierNavigation { get; set; }
        public virtual BillableItemType BillableItemType { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual SuperServiceOrder SuperServiceOrder { get; set; }
        public virtual ICollection<BillableItemAdjustment> BillableItemAdjustment { get; set; }
        public virtual ICollection<GPTransaction> GPTransaction { get; set; }
    }
}