// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class BillableItemStatus
    {
        public BillableItemStatus()
        {
            BillableItem = new HashSet<BillableItem>();
        }

        public string BillableItemStatusIdentifier { get; set; }
        public string BillableItemStatusName { get; set; }
        public string BillableItemStatusDescription { get; set; }

        public virtual ICollection<BillableItem> BillableItem { get; set; }
    }
}