// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class BillableItemAdjustment
    {
        public int Id { get; set; }
        public int BillableItemId { get; set; }
        public int? InvoiceId { get; set; }
        public string AdjustmentType { get; set; }
        public string AdjustmentStatus { get; set; }
        public int SequenceOverBillableItem { get; set; }
        public int? SequenceOverInvoice { get; set; }
        public string GPDocNum { get; set; }
        public decimal OldAmountUSD { get; set; }
        public decimal NewAmountUSD { get; set; }
        public string Explanation { get; set; }
        public string AdjustmentBy { get; set; }
        public DateTime AdjustmentDateTime { get; set; }

        public virtual BillableItem BillableItem { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}