// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class BillableItemType
    {
        public BillableItemType()
        {
            BillableItem = new HashSet<BillableItem>();
            PayableItem = new HashSet<PayableItem>();
        }

        public int Id { get; set; }
        public string AccountCode { get; set; }
        public string BillableItemTypeName { get; set; }
        public bool? IsActive { get; set; }

        public virtual AccountCode AccountCodeNavigation { get; set; }
        public virtual ICollection<BillableItem> BillableItem { get; set; }
        public virtual ICollection<PayableItem> PayableItem { get; set; }
    }
}