// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class Branch
    {
        public Branch()
        {
            Job = new HashSet<Job>();
        }

        public string BranchNameIdentifier { get; set; }
        public string BranchName { get; set; }
        public string BranchCode { get; set; }
        public string SalesDetailBranchCodePart { get; set; }

        public virtual ICollection<Job> Job { get; set; }
    }
}