// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class Configuration
    {
        public int Id { get; set; }
        public string Module { get; set; }
        public string Title { get; set; }
        public int StarCount { get; set; }
        public int MsgMinLength { get; set; }
        public int MsgMaxLength { get; set; }
        public int ToastNotificationTime { get; set; }
        public bool IsActive { get; set; }
    }
}