// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class Document
    {
        public Document()
        {
            DocumentHistory = new HashSet<DocumentHistory>();
        }

        public int Id { get; set; }
        public string FileName { get; set; }
        public string DisplayName { get; set; }
        public string DocType { get; set; }
        public bool IsUploadable { get; set; }
        public bool? IsEnabled { get; set; }

        public virtual ICollection<DocumentHistory> DocumentHistory { get; set; }
    }
}