// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class DocumentHistory
    {
        public int Id { get; set; }
        public DateTime DateUploaded { get; set; }
        public int DocumentId { get; set; }
        public string UserId { get; set; }
        public string Status { get; set; }

        public virtual Document Document { get; set; }
    }
}