// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ExchangeRate
    {
        public int Id { get; set; }
        public DateTime RateDate { get; set; }
        public string BaseCurrency { get; set; }
        public string Currency { get; set; }
        public decimal OriginalRate { get; set; }
        public decimal HedgeAmount { get; set; }
        public decimal HedgedRate { get; set; }
    }
}