// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class GLCode
    {
        public int GPDistType { get; set; }
        public string GPDistTypeMeaning { get; set; }
        public string BranchName { get; set; }
        public string SalesDetailBranchCodePart { get; set; }
        public string ReceivableOrPayable { get; set; }
        public string AccrualOrActual { get; set; }
        public string RevenueType { get; set; }
        public string SalesDetailItemRevenueTypeCodePart { get; set; }
        public string AccountGroupCode { get; set; }
        public string AccountCode { get; set; }
        public string AccountCodeName { get; set; }
        public string GLCode1 { get; set; }
    }
}