// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class GPTransactionType
    {
        public GPTransactionType()
        {
            GPTransaction = new HashSet<GPTransaction>();
        }

        public string GPTransactionTypeIdentifier { get; set; }
        public string GPTransactionTypeName { get; set; }

        public virtual ICollection<GPTransaction> GPTransaction { get; set; }
    }
}