// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class GPTransaction
    {
        public int Id { get; set; }
        public int SuperServiceOrderId { get; set; }
        public int? BillableItemId { get; set; }
        public int? PayableItemId { get; set; }
        public int? InvoiceId { get; set; }
        public int? VendorInvoiceId { get; set; }
        public string GPTransactionTypeIdentifier { get; set; }
        public string GPTransactionStatus { get; set; }
        public string AROrAP { get; set; }
        public string GPDocNum { get; set; }
        public string Accounting_SI_Code { get; set; }
        public int? GPDocType { get; set; }
        public DateTime? GPDocDate { get; set; }
        public DateTime? FinancialPeriodDateTime { get; set; }
        public decimal? CreditAmountUSD { get; set; }
        public decimal? DebitAmountUSD { get; set; }
        public string FailureReason { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual BillableItem BillableItem { get; set; }
        public virtual GPTransactionType GPTransactionTypeIdentifierNavigation { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual PayableItem PayableItem { get; set; }
        public virtual SuperServiceOrder SuperServiceOrder { get; set; }
        public virtual VendorInvoice VendorInvoice { get; set; }
    }
}