// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class IntegrationEventLog
    {
        public Guid EventId { get; set; }
        public string Content { get; set; }
        public DateTime CreationTime { get; set; }
        public int State { get; set; }
        public int TimesSent { get; set; }
        public string EventTypeName { get; set; }
    }
}