// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class Invoice
    {
        public Invoice()
        {
            BillableItem = new HashSet<BillableItem>();
            BillableItemAdjustment = new HashSet<BillableItemAdjustment>();
            GPTransaction = new HashSet<GPTransaction>();
            PaymentReceived = new HashSet<PaymentReceived>();
        }

        public int Id { get; set; }
        public int SuperServiceOrderId { get; set; }
        public string InvoiceType { get; set; }
        public string BillToType { get; set; }
        public int? BillToTransfereeId { get; set; }
        public int? BillToAccountEntityId { get; set; }
        public int? BillToVendorId { get; set; }
        public int SequenceOverSuperServiceOrder { get; set; }
        public string InvoiceNumber { get; set; }
        public DateTime InvoiceDate { get; set; }
        public DateTime? InvoicePostedDateTime { get; set; }
        public string InvoiceStatusIdentifier { get; set; }
        public int? CreditMemoApplyToInvoiceId { get; set; }
        public int? CreditMemoSequenceOverInvoice { get; set; }
        public string CreditMemoExplanation { get; set; }
        public decimal? TotalInvoiceAmount { get; set; }
        public decimal? TotalPaidAmount { get; set; }
        public DateTime? LastPaidDate { get; set; }
        public string LastPaidCheckNumber { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual AccountEntity BillToAccountEntity { get; set; }
        public virtual Transferee BillToTransferee { get; set; }
        public virtual Vendor BillToVendor { get; set; }
        public virtual InvoiceStatus InvoiceStatusIdentifierNavigation { get; set; }
        public virtual SuperServiceOrder SuperServiceOrder { get; set; }
        public virtual ICollection<BillableItem> BillableItem { get; set; }
        public virtual ICollection<BillableItemAdjustment> BillableItemAdjustment { get; set; }
        public virtual ICollection<GPTransaction> GPTransaction { get; set; }
        public virtual ICollection<PaymentReceived> PaymentReceived { get; set; }
    }
}