// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class Job
    {
        public Job()
        {
            AuthorizedRepresentative = new HashSet<AuthorizedRepresentative>();
            JobContact = new HashSet<JobContact>();
            JobSuperServiceAuthorization = new HashSet<JobSuperServiceAuthorization>();
            ServiceBreak = new HashSet<ServiceBreak>();
            ServiceOrder = new HashSet<ServiceOrder>();
            SuperServiceOrder = new HashSet<SuperServiceOrder>();
        }

        public int Id { get; set; }
        public int TransfereeId { get; set; }
        public int? OriginAddressId { get; set; }
        public int? DestinationAddressId { get; set; }
        public int AccountEntityId { get; set; }
        public int? BookerId { get; set; }
        public int BillToId { get; set; }
        public string BillToType { get; set; }
        public string JobSource { get; set; }
        public string JobStatus { get; set; }
        public string AccrualStatus { get; set; }
        public string BranchName { get; set; }
        public string RevenueType { get; set; }
        public string MoveType { get; set; }
        public string AuthorizationPONumber { get; set; }
        public string AccountCustomerReference { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual AccountEntity AccountEntity { get; set; }
        public virtual Vendor Booker { get; set; }
        public virtual Branch BranchNameNavigation { get; set; }
        public virtual Address DestinationAddress { get; set; }
        public virtual JobStatus JobStatusNavigation { get; set; }
        public virtual Address OriginAddress { get; set; }
        public virtual Transferee Transferee { get; set; }
        public virtual JobSurveyInfo JobSurveyInfo { get; set; }
        public virtual TaskOrder TaskOrder { get; set; }
        public virtual ICollection<AuthorizedRepresentative> AuthorizedRepresentative { get; set; }
        public virtual ICollection<JobContact> JobContact { get; set; }
        public virtual ICollection<JobSuperServiceAuthorization> JobSuperServiceAuthorization { get; set; }
        public virtual ICollection<ServiceBreak> ServiceBreak { get; set; }
        public virtual ICollection<ServiceOrder> ServiceOrder { get; set; }
        public virtual ICollection<SuperServiceOrder> SuperServiceOrder { get; set; }
    }
}