// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class JobSuperServiceAuthorization
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public int SuperServiceId { get; set; }
        public decimal Amount { get; set; }
        public string MeasurementType { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateModified { get; set; }

        public virtual Job Job { get; set; }
        public virtual SuperService SuperService { get; set; }
    }
}