// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class JobStatus
    {
        public JobStatus()
        {
            Job = new HashSet<Job>();
        }

        public string JobStatusIdentifier { get; set; }
        public string JobStatusDisplayName { get; set; }
        public string JobStatusDescription { get; set; }

        public virtual ICollection<Job> Job { get; set; }
    }
}