// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class NewMoves
    {
        public int Id { get; set; }
        public string MoveId { get; set; }
        public string OrderNo { get; set; }
        public string PurchaseOrderNo { get; set; }
        public DateTime? SystemDate { get; set; }
        public string AccountId { get; set; }
        public string GroupCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string AccountName { get; set; }
        public string System { get; set; }
        public DateTime CreateDate { get; set; }
    }
}