// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class PayableItemAdjustment
    {
        public int Id { get; set; }
        public int PayableItemId { get; set; }
        public int? VendorInvoiceId { get; set; }
        public string AdjustmentType { get; set; }
        public string AdjustmentStatus { get; set; }
        public int SequenceOverPayableItem { get; set; }
        public int? SequenceOverVendorInvoice { get; set; }
        public string GPDocNum { get; set; }
        public decimal OldAmountUSD { get; set; }
        public decimal NewAmountUSD { get; set; }
        public string Explanation { get; set; }
        public string AdjustmentBy { get; set; }
        public DateTime AdjustmentDateTime { get; set; }

        public virtual PayableItem PayableItem { get; set; }
        public virtual VendorInvoice VendorInvoice { get; set; }
    }
}