// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class PayableItemStatus
    {
        public PayableItemStatus()
        {
            PayableItem = new HashSet<PayableItem>();
        }

        public string PayableItemStatusIdentifier { get; set; }
        public string PayableItemStatusName { get; set; }
        public string PayableItemStatusDescription { get; set; }

        public virtual ICollection<PayableItem> PayableItem { get; set; }
    }
}