// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class PayableItem
    {
        public PayableItem()
        {
            GPTransaction = new HashSet<GPTransaction>();
            PayableItemAdjustment = new HashSet<PayableItemAdjustment>();
        }

        public int Id { get; set; }
        public int SuperServiceOrderId { get; set; }
        public int? BillableItemTypeId { get; set; }
        public string PayableItemStatusIdentifier { get; set; }
        public string BillFromType { get; set; }
        public int? BillFromTransfereeId { get; set; }
        public int? BillFromAccountEntityId { get; set; }
        public int? BillFromVendorId { get; set; }
        public string VendorCurrency { get; set; }
        public string VendorCurrencySymbol { get; set; }
        public string Description { get; set; }
        public bool IsOriginalAccrual { get; set; }
        public decimal? OriginalAccrualAmountVendorCurrency { get; set; }
        public decimal? OriginalAccrualAmountUSD { get; set; }
        public DateTimeOffset? OriginalAccrualPostedDateTime { get; set; }
        public string OriginalAccrualPostedBy { get; set; }
        public decimal? AccrualAmountVendorCurrency { get; set; }
        public decimal? AccrualAmountUSD { get; set; }
        public decimal? AccrualExchangeRate { get; set; }
        public DateTime? AccrualExchangeRateDateTime { get; set; }
        public DateTime? AccrualFinancialPeriodDateTime { get; set; }
        public DateTimeOffset? AccrualPostedDateTime { get; set; }
        public string AccrualPostedBy { get; set; }
        public decimal? OriginalActualAmountVendorCurrency { get; set; }
        public decimal? OriginalActualAmountUSD { get; set; }
        public DateTime? OriginalActualPostedDateTime { get; set; }
        public string OriginalActualPostedBy { get; set; }
        public decimal? ActualAmountVendorCurrency { get; set; }
        public decimal? ActualAmountUSD { get; set; }
        public decimal? ActualExchangeRate { get; set; }
        public DateTime? ActualExchangeRateDateTime { get; set; }
        public DateTime? ActualFinancialPeriodDateTime { get; set; }
        public DateTime? ActualPostedDateTime { get; set; }
        public string ActualPostedBy { get; set; }
        public int? SequenceOverAccountCode { get; set; }
        public string GPDocNum { get; set; }
        public int? VendorInvoiceId { get; set; }
        public string VendorInvoiceNumber { get; set; }
        public DateTime? VendorInvoiceDate { get; set; }
        public string HoldType { get; set; }
        public decimal? WriteOffAmountUSD { get; set; }
        public string WriteOffReason { get; set; }
        public string WriteOffExplanation { get; set; }
        public string WriteOffModifiedBy { get; set; }
        public DateTimeOffset? WriteOffModifiedDateTime { get; set; }
        public bool IsAccrualAdjusted { get; set; }
        public string AccrualAdjustmentBy { get; set; }
        public DateTime? AccrualAdjustmentDateTime { get; set; }
        public bool IsActualAdjusted { get; set; }
        public string ActualAdjustmentBy { get; set; }
        public DateTime? ActualAdjustmentDateTime { get; set; }
        public string VoidedBy { get; set; }
        public DateTimeOffset? VoidedDateTime { get; set; }
        public DateTime? VoidedFinancialPeriodDate { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual AccountEntity BillFromAccountEntity { get; set; }
        public virtual Transferee BillFromTransferee { get; set; }
        public virtual Vendor BillFromVendor { get; set; }
        public virtual BillableItemType BillableItemType { get; set; }
        public virtual PayableItemStatus PayableItemStatusIdentifierNavigation { get; set; }
        public virtual SuperServiceOrder SuperServiceOrder { get; set; }
        public virtual VendorInvoice VendorInvoice { get; set; }
        public virtual ICollection<GPTransaction> GPTransaction { get; set; }
        public virtual ICollection<PayableItemAdjustment> PayableItemAdjustment { get; set; }
    }
}