// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class PaymentReceived
    {
        public int Id { get; set; }
        public int? InvoiceId { get; set; }
        public string Accounting_SI_Code { get; set; }
        public string InvoiceNumber { get; set; }
        public string GPPaymentDocNum { get; set; }
        public string CheckNumber { get; set; }
        public DateTime PaidDate { get; set; }
        public decimal Amount { get; set; }
        public bool IsVoided { get; set; }
        public DateTime? VoidedFinancialPeriodDate { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Invoice Invoice { get; set; }
    }
}