// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class PaymentRequest
    {
        public PaymentRequest()
        {
            ServiceItem = new HashSet<ServiceItem>();
        }

        public int Id { get; set; }
        public int JobId { get; set; }
        public string PaymentRequestStatusIdentifier { get; set; }
        public DateTime? PaymentRequestDateTime { get; set; }
        public string GovPaymentRequestNumber { get; set; }
        public DateTime? UpdatedDateTime { get; set; }
        public string GovRejectionReason { get; set; }
        public string HomeFrontRejectionReason { get; set; }
        public decimal? RequestedTotalAmountUSD { get; set; }
        public decimal? ApprovedTotalAmountUSD { get; set; }
        public string GovInvoiceNumber { get; set; }
        public decimal? AmountPaidByTppsToArcUSD { get; set; }
        public bool IsFinished { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual TaskOrder Job { get; set; }
        public virtual PaymentRequestStatus PaymentRequestStatusIdentifierNavigation { get; set; }
        public virtual ICollection<ServiceItem> ServiceItem { get; set; }
    }
}