// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class PaymentRequestStatus
    {
        public PaymentRequestStatus()
        {
            PaymentRequest = new HashSet<PaymentRequest>();
            ServiceItem = new HashSet<ServiceItem>();
        }

        public string PaymentRequestStatusIdentifier { get; set; }
        public string PaymentRequestStatusName { get; set; }
        public string PaymentRequestStatusDescription { get; set; }

        public virtual ICollection<PaymentRequest> PaymentRequest { get; set; }
        public virtual ICollection<ServiceItem> ServiceItem { get; set; }
    }
}