// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class Phone
    {
        public Phone()
        {
            AuthorizedRepresentativePhone = new HashSet<AuthorizedRepresentativePhone>();
            TransfereePhone = new HashSet<TransfereePhone>();
        }

        public int Id { get; set; }
        public string NationalNumber { get; set; }
        public bool? Primary { get; set; }
        public string Extension { get; set; }
        public string Type { get; set; }
        public string DialCode { get; set; }
        public string CountryCode { get; set; }

        public virtual ICollection<AuthorizedRepresentativePhone> AuthorizedRepresentativePhone { get; set; }
        public virtual ICollection<TransfereePhone> TransfereePhone { get; set; }
    }
}