// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderClaimSettlement
    {
        public int Id { get; set; }
        public int ServiceOrderInsuranceClaimId { get; set; }
        public DateTime? SettlementOfferedDate { get; set; }
        public decimal? SettlementOfferedAmount { get; set; }
        public DateTime? SettlementAcceptedDate { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ServiceOrderInsuranceClaim ServiceOrderInsuranceClaim { get; set; }
    }
}