// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceItem
    {
        public ServiceItem()
        {
            ServiceItemDetail = new HashSet<ServiceItemDetail>();
        }

        public int Id { get; set; }
        public int JobId { get; set; }
        public int? SuperServiceOrderId { get; set; }
        public int? ApprovalRequestId { get; set; }
        public int? PaymentRequestId { get; set; }
        public string ServiceItemIdentifier { get; set; }
        public string SourceSystem { get; set; }
        public string ServiceItemStatusIdentifier { get; set; }
        public DateTime? LastAdjudicatedDateTime { get; set; }
        public string AdjudicatedReason { get; set; }
        public string RequestedServiceIdentifier { get; set; }
        public string RequestedServiceCode { get; set; }
        public string Reason { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string PickupPostalCode { get; set; }
        public string ShuttlePickupAddress { get; set; }
        public DateTime? TimeMilitary1 { get; set; }
        public DateTime? TimeMilitary2 { get; set; }
        public DateTime? FirstAvailableDeliveryDateTime1 { get; set; }
        public DateTime? FirstAvailableDeliveryDateTime2 { get; set; }
        public string ItemDimensionIdentifier { get; set; }
        public int? ItemLength { get; set; }
        public int? ItemWidth { get; set; }
        public int? ItemHeight { get; set; }
        public string CrateDimensionIdentifier { get; set; }
        public int? CrateLength { get; set; }
        public int? CrateWidth { get; set; }
        public int? CrateHeight { get; set; }
        public DateTime? SitInDate { get; set; }
        public DateTime? FirstAvailableDate { get; set; }
        public decimal? SitWeight { get; set; }
        public int? SitDaysRequested { get; set; }
        public string ServiceItemPaymentRequestStatusIdentifier { get; set; }
        public string GovPaymentRequestIdentifier { get; set; }
        public decimal? RequestedPriceUSD { get; set; }
        public decimal? HomefrontPriceUSD { get; set; }
        public decimal? GovPriceUSD { get; set; }
        public string HomeFrontRejectionReason { get; set; }
        public string GovRejectionReason { get; set; }
        public bool IsCompleted { get; set; }
        public DateTime? CompletedDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ApprovalRequest ApprovalRequest { get; set; }
        public virtual TaskOrder Job { get; set; }
        public virtual PaymentRequest PaymentRequest { get; set; }
        public virtual ServiceCode RequestedServiceCodeNavigation { get; set; }
        public virtual PaymentRequestStatus ServiceItemPaymentRequestStatusIdentifierNavigation { get; set; }
        public virtual ServiceItemStatus ServiceItemStatusIdentifierNavigation { get; set; }
        public virtual Shipment SuperServiceOrder { get; set; }
        public virtual ICollection<ServiceItemDetail> ServiceItemDetail { get; set; }
    }
}