// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderOceanFreightContainer
    {
        public ServiceOrderOceanFreightContainer()
        {
            ServiceOrderOceanFreightLiftVan = new HashSet<ServiceOrderOceanFreightLiftVan>();
            ServiceOrderOceanFreightLooseItem = new HashSet<ServiceOrderOceanFreightLooseItem>();
            ServiceOrderOceanFreightVehicle = new HashSet<ServiceOrderOceanFreightVehicle>();
        }

        public int Id { get; set; }
        public int ServiceOrderId { get; set; }
        public string ContainerType { get; set; }
        public string ContainerNumber { get; set; }
        public string SealNumber { get; set; }
        public int? NumberOfItems { get; set; }
        public decimal? TareWeightLb { get; set; }
        public string Description { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ServiceOrder ServiceOrder { get; set; }
        public virtual ICollection<ServiceOrderOceanFreightLiftVan> ServiceOrderOceanFreightLiftVan { get; set; }
        public virtual ICollection<ServiceOrderOceanFreightLooseItem> ServiceOrderOceanFreightLooseItem { get; set; }
        public virtual ICollection<ServiceOrderOceanFreightVehicle> ServiceOrderOceanFreightVehicle { get; set; }
    }
}