// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderStatus
    {
        public ServiceOrderStatus()
        {
            ServiceOrder = new HashSet<ServiceOrder>();
        }

        public string ServiceOrderStatusIdentifier { get; set; }
        public string ServiceOrderStatusDisplayName { get; set; }
        public string ServiceOrderStatusDescription { get; set; }

        public virtual ICollection<ServiceOrder> ServiceOrder { get; set; }
    }
}