// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceBreak
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public bool? PositiveFeedback { get; set; }
        public int VendorId { get; set; }
        public bool? ReportToAgent { get; set; }
        public string Issue { get; set; }
        public string Resolution { get; set; }
        public bool? IsResolved { get; set; }
        public DateTime? ResolvedDay { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Job Job { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}