// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderThirdPartyCrate
    {
        public int Id { get; set; }
        public int ServiceOrderId { get; set; }
        public DateTime? ServiceDate { get; set; }
        public string OriginOrDestination { get; set; }
        public string Description { get; set; }
        public string CrateType { get; set; }
        public int? Quantity { get; set; }
        public bool IsMetric { get; set; }
        public decimal? Length { get; set; }
        public decimal? Width { get; set; }
        public decimal? Depth { get; set; }
        public decimal? Volume { get; set; }
        public decimal? Cost { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ServiceOrder ServiceOrder { get; set; }
    }
}