// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderMoveInfo
    {
        public int ServiceOrderId { get; set; }
        public decimal? QuotedRate { get; set; }
        public string QuotedUnit { get; set; }
        public string Currency { get; set; }
        public decimal? QuoteTotal { get; set; }
        public DateTime? EstimatedPackStartDate { get; set; }
        public DateTime? EstimatedPackEndDate { get; set; }
        public TimeSpan? EstimatedPackStartTime { get; set; }
        public TimeSpan? EstimatedPackEndTime { get; set; }
        public DateTime? ActualPackStartDate { get; set; }
        public DateTime? ActualPackEndDate { get; set; }
        public DateTime? EstimatedPickupStartDate { get; set; }
        public DateTime? EstimatedPickupEndDate { get; set; }
        public DateTime? ActualPickupStartDate { get; set; }
        public DateTime? ActualPickupEndDate { get; set; }
        public string CrewLeaderName { get; set; }
        public DateTime? OAInstructionsSentDate { get; set; }
        public DateTime? OAFinalsReceivedDate { get; set; }
        public DateTime? OAGreenLightDate { get; set; }
        public DateTime? OASubmittedToFMCDate { get; set; }
        public bool IsSITAuthorized { get; set; }
        public DateTime? SITInDate { get; set; }
        public DateTime? SITOutDate { get; set; }
        public int? SITDaysAuthorized { get; set; }
        public DateTime? SITLastAuthorizedDate { get; set; }
        public int? SITDaysUsed { get; set; }
        public decimal? NetWeightLb { get; set; }
        public decimal? NetWeightKg { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ServiceOrder ServiceOrder { get; set; }
    }
}