// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderInsuranceClaim
    {
        public ServiceOrderInsuranceClaim()
        {
            ServiceOrderClaimDamage = new HashSet<ServiceOrderClaimDamage>();
            ServiceOrderClaimInspection = new HashSet<ServiceOrderClaimInspection>();
            ServiceOrderClaimRepair = new HashSet<ServiceOrderClaimRepair>();
            ServiceOrderClaimSettlement = new HashSet<ServiceOrderClaimSettlement>();
        }

        public int Id { get; set; }
        public int ServiceOrderId { get; set; }
        public string InsuranceCarrierName { get; set; }
        public string Declaration { get; set; }
        public string InsuranceType { get; set; }
        public decimal? HHGAmount { get; set; }
        public decimal? HighValueAmount { get; set; }
        public decimal? VehicleAmount { get; set; }
        public decimal? TotalInsuranceAmount { get; set; }
        public decimal? DeductibleAmount { get; set; }
        public decimal? QuotedRate { get; set; }
        public decimal? PayableRate { get; set; }
        public string PayableRateType { get; set; }
        public bool CanIssuePolicy { get; set; }
        public string ClaimStatus { get; set; }
        public string ClaimNumber { get; set; }
        public DateTime? InactivityClosedDate { get; set; }
        public DateTime? ClaimDate { get; set; }
        public decimal? ClaimedAmount { get; set; }
        public DateTime? ClaimantDocsCreatedDate { get; set; }
        public DateTime? AssigneePaidDate { get; set; }
        public decimal? PaidAmount { get; set; }
        public decimal? GoodwillAmount { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ServiceOrder ServiceOrder { get; set; }
        public virtual ICollection<ServiceOrderClaimDamage> ServiceOrderClaimDamage { get; set; }
        public virtual ICollection<ServiceOrderClaimInspection> ServiceOrderClaimInspection { get; set; }
        public virtual ICollection<ServiceOrderClaimRepair> ServiceOrderClaimRepair { get; set; }
        public virtual ICollection<ServiceOrderClaimSettlement> ServiceOrderClaimSettlement { get; set; }
    }
}