// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderOceanFreightVehicle
    {
        public int Id { get; set; }
        public int ServiceOrderId { get; set; }
        public int? ServiceOrderOceanFreightContainerId { get; set; }
        public string VehicleType { get; set; }
        public string VIN { get; set; }
        public string TitleNumber { get; set; }
        public decimal? WeightLb { get; set; }
        public decimal? VolumeCUFT { get; set; }
        public decimal? VehicleValue { get; set; }
        public string VehicleYear { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleColor { get; set; }
        public DateTime? TitleFromShipperReceivedDate { get; set; }
        public DateTime? DrainStatementReceivedDate { get; set; }
        public DateTime? TitleToShipperSentDate { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ServiceOrder ServiceOrder { get; set; }
        public virtual ServiceOrderOceanFreightContainer ServiceOrderOceanFreightContainer { get; set; }
    }
}