// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderStorageRevenue
    {
        public int Id { get; set; }
        public int ServiceOrderId { get; set; }
        public int? BillToTransfereeId { get; set; }
        public int? BillToAccountEntityId { get; set; }
        public int? BillToVendorId { get; set; }
        public string BillToType { get; set; }
        public string ContactEmail { get; set; }
        public decimal? StorageBillableWeightLb { get; set; }
        public DateTime? StorageEffectiveBillDate { get; set; }
        public DateTime? BillingRecordEndDate { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsArrears { get; set; }
        public string StorageCurrency { get; set; }
        public decimal? StorageCostRate { get; set; }
        public string StorageCostUnit { get; set; }
        public string InsuranceCurrency { get; set; }
        public decimal? InsuranceCostRate { get; set; }
        public string InsuranceCostUnit { get; set; }
        public string BillingCycle { get; set; }
        public DateTime? FreePeriodStartDate { get; set; }
        public DateTime? FreePeriodEndDate { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual AccountEntity BillToAccountEntity { get; set; }
        public virtual Transferee BillToTransferee { get; set; }
        public virtual Vendor BillToVendor { get; set; }
        public virtual ServiceOrder ServiceOrder { get; set; }
    }
}