// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceItemStatus
    {
        public ServiceItemStatus()
        {
            ServiceItem = new HashSet<ServiceItem>();
        }

        public string ServiceItemStatusIdentifier { get; set; }
        public string ServiceItemStatusName { get; set; }
        public string ServiceItemStatusDescription { get; set; }

        public virtual ICollection<ServiceItem> ServiceItem { get; set; }
    }
}