// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceCategory
    {
        public ServiceCategory()
        {
            SuperService = new HashSet<SuperService>();
        }

        public int Id { get; set; }
        public string ServiceCategoryName { get; set; }

        public virtual ICollection<SuperService> SuperService { get; set; }
    }
}