// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceItemDetail
    {
        public int Id { get; set; }
        public int ServiceItemId { get; set; }
        public string ServiceItemDetailType { get; set; }
        public DateTime ServiceItemDetailDateTime { get; set; }
        public string ServiceItemJson { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ServiceItem ServiceItem { get; set; }

        [NotMapped]
        public virtual ServiceItem ServiceItemArchive { get; set; }
    }
}