// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderDestinationAgent
    {
        public int ServiceOrderId { get; set; }
        public decimal? QuotedRate { get; set; }
        public string QuotedUnit { get; set; }
        public string Currency { get; set; }
        public decimal? QuoteTotal { get; set; }
        public DateTime? RequestedDeliveryStartDate { get; set; }
        public DateTime? RequestedDeliveryEndDate { get; set; }
        public DateTime? ScheduledDeliveryStartDate { get; set; }
        public DateTime? ScheduledDeliveryEndDate { get; set; }
        public TimeSpan? ScheduledDeliveryStartTime { get; set; }
        public TimeSpan? ScheduledDeliveryEndTime { get; set; }
        public DateTime? ActualDeliveryStartDate { get; set; }
        public DateTime? ActualDeliveryEndDate { get; set; }
        public DateTime? ActualUnpackStartDate { get; set; }
        public DateTime? ActualUnpackEndDate { get; set; }
        public string CrewLeaderName { get; set; }
        public DateTime? DocumentsOutDate { get; set; }
        public DateTime? PreAdviceSentDate { get; set; }
        public DateTime? SignedDeliveryDocumentsReceivedDate { get; set; }
        public decimal? ReweighWeightLb { get; set; }
        public decimal? TotalWeightDeliveredLb { get; set; }
        public decimal? RemainingWeightToDeliverLb { get; set; }
        public DateTime? SITInDate { get; set; }
        public DateTime? SITOutDate { get; set; }
        public int? SITDaysAuthorized { get; set; }
        public DateTime? SITLastAuthorizedDate { get; set; }
        public int? SITDaysUsed { get; set; }
        public bool IsSITAuthorized { get; set; }
        public string AgentType { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ServiceOrder ServiceOrder { get; set; }
    }
}