// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderStorage
    {
        public int ServiceOrderId { get; set; }
        public string StorageCurrency { get; set; }
        public decimal? StorageCostRate { get; set; }
        public string StorageCostUnit { get; set; }
        public string InsuranceCurrency { get; set; }
        public decimal? InsuranceCostRate { get; set; }
        public string InsuranceCostUnit { get; set; }
        public string AgentType { get; set; }
        public DateTime? ActualDateIn { get; set; }
        public DateTime? ActualDateOut { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ServiceOrder ServiceOrder { get; set; }
    }
}