// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderThirdParty
    {
        public int ServiceOrderId { get; set; }
        public string Currency { get; set; }
        public decimal? QuoteTotal { get; set; }
        public decimal? TotalCrateVolumeCUFT { get; set; }
        public DateTime? RequestedServiceDate { get; set; }
        public DateTime? ActualServiceDate { get; set; }
        public string ContractType { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ServiceOrder ServiceOrder { get; set; }
    }
}