// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderAirFreight
    {
        public int ServiceOrderId { get; set; }
        public decimal? QuotedRate { get; set; }
        public string QuotedUnit { get; set; }
        public string Currency { get; set; }
        public decimal? QuoteTotal { get; set; }
        public int? CarrierVendorId { get; set; }
        public string MasterAwbNumber { get; set; }
        public string HouseAirwayBillNumber { get; set; }
        public DateTime? BookingDate { get; set; }
        public string XTNNumber { get; set; }
        public string ITNNumber { get; set; }
        public DateTime? ITNFiledDate { get; set; }
        public string EINNumber { get; set; }
        public string CountryOfIssue { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Vendor CarrierVendor { get; set; }
        public virtual ServiceOrder ServiceOrder { get; set; }
    }
}