// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderLineHaul
    {
        public int ServiceOrderId { get; set; }
        public string Currency { get; set; }
        public decimal? QuotedRate { get; set; }
        public decimal? FSC { get; set; }
        public decimal? ChassisCost { get; set; }
        public bool IsChassisProvided { get; set; }
        public decimal? QuoteTotal { get; set; }
        public string AgentType { get; set; }
        public string LineHaulType { get; set; }
        public string LocationType { get; set; }
        public DateTime? SendOrderDate { get; set; }
        public DateTime? LastFreeDate { get; set; }
        public DateTime? LastFreeDateAtPort { get; set; }
        public DateTime? LiveLoadDate { get; set; }
        public DateTime? LiveUnloadDate { get; set; }
        public DateTime? RequestedPickupDate { get; set; }
        public DateTime? ActualPickupDate { get; set; }
        public DateTime? RequestedDropDate { get; set; }
        public DateTime? ActualDropDate { get; set; }
        public int? FreeDays { get; set; }
        public string DaysType { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ServiceOrder ServiceOrder { get; set; }
    }
}