// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderDestinationAgentPartialDelivery
    {
        public int Id { get; set; }
        public int ServiceOrderId { get; set; }
        public DateTime? PartialDeliveryDate { get; set; }
        public decimal? WeightDeliveredLb { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ServiceOrder ServiceOrder { get; set; }
    }
}