// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class ServiceOrderCustomClearance
    {
        public int ServiceOrderId { get; set; }
        public string AgentType { get; set; }
        public string Currency { get; set; }
        public decimal? QuoteTotal { get; set; }
        public DateTime? CustomsEntryDate { get; set; }
        public DateTime? CustomsReleaseDate { get; set; }
        public DateTime? DocumentOutDate { get; set; }
        public string ISFReferenceNumber { get; set; }
        public DateTime? ISFDocumentReceivedDate { get; set; }
        public DateTime? ISFSendDate { get; set; }
        public DateTime? ISFReceivedDate { get; set; }
        public DateTime? ISFMatchDate { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual ServiceOrder ServiceOrder { get; set; }
    }
}