// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class Shipment
    {
        public Shipment()
        {
            Activity = new HashSet<Activity>();
            ServiceItem = new HashSet<ServiceItem>();
        }

        public int SuperServiceOrderId { get; set; }
        public int JobId { get; set; }
        public string ShipmentIdentifier { get; set; }
        public int? PickupAddressId { get; set; }
        public int? DestinationAddressId { get; set; }
        public int? SecondaryPickupAddressId { get; set; }
        public int? SecondaryDestinationAddressId { get; set; }
        public string ShipmentType { get; set; }
        public DateTime? ApprovedDateTime { get; set; }
        public DateTime? RequestedPickupDateTime { get; set; }
        public DateTime? RequiredDeliveryDateTime { get; set; }
        public string CustomerRemarks { get; set; }
        public decimal? EstimatedWeightLb { get; set; }
        public DateTime? SentToAwardManagementDateTime { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual TaskOrder Job { get; set; }
        public virtual SuperServiceOrder SuperServiceOrder { get; set; }
        public virtual ICollection<Activity> Activity { get; set; }
        public virtual ICollection<ServiceItem> ServiceItem { get; set; }
    }
}