// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class SuperServiceOrderCrate
    {
        public int Id { get; set; }
        public int SuperServiceOrderId { get; set; }
        public string Description { get; set; }
        public decimal? Length { get; set; }
        public decimal? Width { get; set; }
        public decimal? Depth { get; set; }
        public bool IsMetric { get; set; }
        public string Type { get; set; }
        public int? Count { get; set; }

        public virtual SuperServiceOrder SuperServiceOrder { get; set; }
    }
}