// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class SuperServiceMode
    {
        public SuperServiceMode()
        {
            SuperServiceOrder = new HashSet<SuperServiceOrder>();
        }

        public int Id { get; set; }
        public int SuperServiceId { get; set; }
        public string ModeName { get; set; }
        public string AvailableTo { get; set; }

        public virtual SuperService SuperService { get; set; }
        public virtual ICollection<SuperServiceOrder> SuperServiceOrder { get; set; }
    }
}