// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class SuperServiceOrder
    {
        public SuperServiceOrder()
        {
            BillableItem = new HashSet<BillableItem>();
            GPTransaction = new HashSet<GPTransaction>();
            Invoice = new HashSet<Invoice>();
            PayableItem = new HashSet<PayableItem>();
            ServiceOrder = new HashSet<ServiceOrder>();
            SuperServiceOrderAccessorial = new HashSet<SuperServiceOrderAccessorial>();
            SuperServiceOrderCrate = new HashSet<SuperServiceOrderCrate>();
            VendorInvoice = new HashSet<VendorInvoice>();
        }

        public int Id { get; set; }
        public int JobId { get; set; }
        public int SequenceNumber { get; set; }
        public string DisplayId { get; set; }
        public int SuperServiceId { get; set; }
        public int TransfereeId { get; set; }
        public string SuperServiceOrderStatusIdentifier { get; set; }
        public int? SuperServiceModeId { get; set; }
        public bool IsAuthorized { get; set; }
        public string AccrualStatus { get; set; }
        public DateTime? AccrualPendingDateTime { get; set; }
        public DateTime? AccrualPostedDateTime { get; set; }
        public bool? IsSurveySent { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Job Job { get; set; }
        public virtual SuperService SuperService { get; set; }
        public virtual SuperServiceMode SuperServiceMode { get; set; }
        public virtual SuperServiceOrderStatus SuperServiceOrderStatusIdentifierNavigation { get; set; }
        public virtual Transferee Transferee { get; set; }
        public virtual Shipment Shipment { get; set; }
        public virtual SuperServiceOrderSurveyResult SuperServiceOrderSurveyResult { get; set; }
        public virtual ICollection<BillableItem> BillableItem { get; set; }
        public virtual ICollection<GPTransaction> GPTransaction { get; set; }
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual ICollection<PayableItem> PayableItem { get; set; }
        public virtual ICollection<ServiceOrder> ServiceOrder { get; set; }
        public virtual ICollection<SuperServiceOrderAccessorial> SuperServiceOrderAccessorial { get; set; }
        public virtual ICollection<SuperServiceOrderCrate> SuperServiceOrderCrate { get; set; }
        public virtual ICollection<VendorInvoice> VendorInvoice { get; set; }
    }
}