// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class SuperServiceOrderStatus
    {
        public SuperServiceOrderStatus()
        {
            SuperServiceOrder = new HashSet<SuperServiceOrder>();
        }

        public string SuperServiceOrderStatusIdentifier { get; set; }
        public string SuperServiceOrderStatusDisplayName { get; set; }
        public string SuperServiceOrderStatusDescription { get; set; }

        public virtual ICollection<SuperServiceOrder> SuperServiceOrder { get; set; }
    }
}