// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class SuperService
    {
        public SuperService()
        {
            JobSuperServiceAuthorization = new HashSet<JobSuperServiceAuthorization>();
            SuperServiceMode = new HashSet<SuperServiceMode>();
            SuperServiceOrder = new HashSet<SuperServiceOrder>();
        }

        public int Id { get; set; }
        public int ServiceCategoryId { get; set; }
        public string SuperServiceName { get; set; }
        public string SuperServiceIconName { get; set; }

        public virtual ServiceCategory ServiceCategory { get; set; }
        public virtual ICollection<JobSuperServiceAuthorization> JobSuperServiceAuthorization { get; set; }
        public virtual ICollection<SuperServiceMode> SuperServiceMode { get; set; }
        public virtual ICollection<SuperServiceOrder> SuperServiceOrder { get; set; }
    }
}