// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class SuperServiceOrderSurveyResult
    {
        public int SuperServiceOrderId { get; set; }
        public decimal? GrossWeightLb { get; set; }
        public decimal? GrossWeightKg { get; set; }
        public decimal? NetWeightLb { get; set; }
        public decimal? NetWeightKg { get; set; }
        public decimal? GrossVolumeCUFT { get; set; }
        public decimal? GrossVolumeCBM { get; set; }
        public decimal? NetVolumeCUFT { get; set; }
        public decimal? NetVolumeCBM { get; set; }
        public decimal? ACWLb { get; set; }
        public decimal? ACWKg { get; set; }
        public decimal? TotalCrateVolumeCUFT { get; set; }
        public decimal? TotalCrateVolumeCBM { get; set; }

        public virtual SuperServiceOrder SuperServiceOrder { get; set; }
    }
}