// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class TaskOrder
    {
        public TaskOrder()
        {
            Activity = new HashSet<Activity>();
            PaymentRequest = new HashSet<PaymentRequest>();
            ServiceItem = new HashSet<ServiceItem>();
            Shipment = new HashSet<Shipment>();
        }

        public int JobId { get; set; }
        public string TaskOrderIdentifier { get; set; }
        public string MovePriorityType { get; set; }
        public bool IsBlueBark { get; set; }
        public bool IsSafeMove { get; set; }
        public string CET { get; set; }
        public string OperationsTeam { get; set; }
        public string AuthorizedRepresentative { get; set; }
        public string PreferredName { get; set; }
        public string PreferredContactMethod { get; set; }
        public string MovePriority { get; set; }
        public string TaskOrderStatus { get; set; }
        public string OrderType { get; set; }
        public string ServiceMemberIdentifier { get; set; }
        public string ServiceMemberDODIdentifier { get; set; }
        public string ServiceMemberBranch { get; set; }
        public string ServiceMemberRank { get; set; }
        public string ServiceMemberPrimaryCommunicationPreference { get; set; }
        public string ServiceMemberSecondaryCommunicationPreference { get; set; }
        public string Notes { get; set; }
        public int? OriginDutyStationAddressId { get; set; }
        public string OriginDutyStationName { get; set; }
        public int? DestinationDutyStationAddressId { get; set; }
        public string DestinationDutyStationName { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Address DestinationDutyStationAddress { get; set; }
        public virtual Job Job { get; set; }
        public virtual Address OriginDutyStationAddress { get; set; }
        public virtual Entitlement Entitlement { get; set; }
        public virtual ICollection<Activity> Activity { get; set; }
        public virtual ICollection<PaymentRequest> PaymentRequest { get; set; }
        public virtual ICollection<ServiceItem> ServiceItem { get; set; }
        public virtual ICollection<Shipment> Shipment { get; set; }
    }
}