// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class Template
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int TemplateTypeId { get; set; }
        public int TemplatePackId { get; set; }
        public string RazorTemplate { get; set; }
        public DateTime? LastRequestedAtUtc { get; set; }
        public DateTime UpdatedAtUtc { get; set; }

        public virtual TemplatePack TemplatePack { get; set; }
        public virtual TemplateType TemplateType { get; set; }
    }
}