// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class TransfereePhone
    {
        public int TransfereeId { get; set; }
        public int PhoneId { get; set; }
        public string Type { get; set; }

        public virtual Phone Phone { get; set; }
        public virtual Transferee Transferee { get; set; }
    }
}