// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class Transferee
    {
        public Transferee()
        {
            BillableItem = new HashSet<BillableItem>();
            Email = new HashSet<Email>();
            Invoice = new HashSet<Invoice>();
            Job = new HashSet<Job>();
            PayableItem = new HashSet<PayableItem>();
            ServiceOrder = new HashSet<ServiceOrder>();
            ServiceOrderStorageRevenue = new HashSet<ServiceOrderStorageRevenue>();
            SuperServiceOrder = new HashSet<SuperServiceOrder>();
            TransfereePhone = new HashSet<TransfereePhone>();
            VendorInvoice = new HashSet<VendorInvoice>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public bool IsVip { get; set; }
        public int AccountingId { get; set; }

        public virtual ICollection<BillableItem> BillableItem { get; set; }
        public virtual ICollection<Email> Email { get; set; }
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual ICollection<Job> Job { get; set; }
        public virtual ICollection<PayableItem> PayableItem { get; set; }
        public virtual ICollection<ServiceOrder> ServiceOrder { get; set; }
        public virtual ICollection<ServiceOrderStorageRevenue> ServiceOrderStorageRevenue { get; set; }
        public virtual ICollection<SuperServiceOrder> SuperServiceOrder { get; set; }
        public virtual ICollection<TransfereePhone> TransfereePhone { get; set; }
        public virtual ICollection<VendorInvoice> VendorInvoice { get; set; }
    }
}