// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class VendorInvoiceStatus
    {
        public VendorInvoiceStatus()
        {
            VendorInvoice = new HashSet<VendorInvoice>();
        }

        public string VendorInvoiceStatusIdentifier { get; set; }
        public string VendorInvoiceStatusName { get; set; }
        public string VendorInvoiceStatusDescription { get; set; }

        public virtual ICollection<VendorInvoice> VendorInvoice { get; set; }
    }
}