// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class Vendor
    {
        public Vendor()
        {
            ActivityDetail = new HashSet<ActivityDetail>();
            BillableItem = new HashSet<BillableItem>();
            Invoice = new HashSet<Invoice>();
            Job = new HashSet<Job>();
            JobSurveyInfo = new HashSet<JobSurveyInfo>();
            PayableItem = new HashSet<PayableItem>();
            ServiceBreak = new HashSet<ServiceBreak>();
            ServiceOrder = new HashSet<ServiceOrder>();
            ServiceOrderAirFreight = new HashSet<ServiceOrderAirFreight>();
            ServiceOrderOceanFreight = new HashSet<ServiceOrderOceanFreight>();
            ServiceOrderRoadFreight = new HashSet<ServiceOrderRoadFreight>();
            ServiceOrderStorageRevenue = new HashSet<ServiceOrderStorageRevenue>();
            VendorInvoice = new HashSet<VendorInvoice>();
        }

        public int Id { get; set; }
        public int? PrimaryAddressId { get; set; }
        public string Name { get; set; }
        public string Website { get; set; }
        public string Accounting_SI_Code { get; set; }
        public string Accounting_MIL_Code { get; set; }
        public bool IsActive { get; set; }
        public string Source { get; set; }
        public string ShortAddress { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual Address PrimaryAddress { get; set; }
        public virtual ICollection<ActivityDetail> ActivityDetail { get; set; }
        public virtual ICollection<BillableItem> BillableItem { get; set; }
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual ICollection<Job> Job { get; set; }
        public virtual ICollection<JobSurveyInfo> JobSurveyInfo { get; set; }
        public virtual ICollection<PayableItem> PayableItem { get; set; }
        public virtual ICollection<ServiceBreak> ServiceBreak { get; set; }
        public virtual ICollection<ServiceOrder> ServiceOrder { get; set; }
        public virtual ICollection<ServiceOrderAirFreight> ServiceOrderAirFreight { get; set; }
        public virtual ICollection<ServiceOrderOceanFreight> ServiceOrderOceanFreight { get; set; }
        public virtual ICollection<ServiceOrderRoadFreight> ServiceOrderRoadFreight { get; set; }
        public virtual ICollection<ServiceOrderStorageRevenue> ServiceOrderStorageRevenue { get; set; }
        public virtual ICollection<VendorInvoice> VendorInvoice { get; set; }
    }
}