// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Suddath.Helix.JobMgmt.Infrastructure.Domain
{
    public partial class VendorInvoice
    {
        public VendorInvoice()
        {
            GPTransaction = new HashSet<GPTransaction>();
            PayableItem = new HashSet<PayableItem>();
            PayableItemAdjustment = new HashSet<PayableItemAdjustment>();
            PaymentSent = new HashSet<PaymentSent>();
        }

        public int Id { get; set; }
        public string VendorInvoiceType { get; set; }
        public string BillFromType { get; set; }
        public int? BillFromTransfereeId { get; set; }
        public int? BillFromAccountEntityId { get; set; }
        public int? BillFromVendorId { get; set; }
        public int SuperServiceOrderId { get; set; }
        public int SequenceOverSuperServiceOrder { get; set; }
        public string VendorInvoiceNumber { get; set; }
        public DateTime VendorInvoiceDate { get; set; }
        public string GPDocNum { get; set; }
        public DateTime? VendorInvoicePostedDateTime { get; set; }
        public string VendorInvoiceStatusIdentifier { get; set; }
        public int? CreditMemoApplyToVendorInvoiceId { get; set; }
        public int? CreditMemoSequenceOverVendorInvoice { get; set; }
        public string CreditMemoExplanation { get; set; }
        public decimal? TotalVendorInvoiceAmount { get; set; }
        public decimal? TotalPaidAmount { get; set; }
        public DateTime? LastPaidDate { get; set; }
        public string LastPaidCheckNumber { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }

        public virtual AccountEntity BillFromAccountEntity { get; set; }
        public virtual Transferee BillFromTransferee { get; set; }
        public virtual Vendor BillFromVendor { get; set; }
        public virtual SuperServiceOrder SuperServiceOrder { get; set; }
        public virtual VendorInvoiceStatus VendorInvoiceStatusIdentifierNavigation { get; set; }
        public virtual ICollection<GPTransaction> GPTransaction { get; set; }
        public virtual ICollection<PayableItem> PayableItem { get; set; }
        public virtual ICollection<PayableItemAdjustment> PayableItemAdjustment { get; set; }
        public virtual ICollection<PaymentSent> PaymentSent { get; set; }
    }
}